#ifndef SPARSEPC_VERSION_HPP
#define SPARSEPC_VERSION_HPP

#define SPARSEPC_STRINGIFY(x) #x
#define SPARSEPC_MACRO_STRINGIFY(x) SPARSEPC_STRINGIFY(x)

#define SPARSEPC_VERSION_MAJOR 0
#define SPARSEPC_VERSION_MINOR 1
#define SPARSEPC_VERSION_PATCH 0

#define SPARSEPC_VERSION                                                       \
    SPARSEPC_VERSION_MAJOR.SPARSEPC_VERSION_MINOR.SPARSEPC_VERSION_PATCH

#endif // SPARSEPC_VERSION_HPP
