; Example content of maintenance_tool.ini
[General]
# Custom description
Description=Maintenance tool for Sparsely

# Example: Points to where the maintenance tool finds updates
# (This can also be configured via cpack_ifw_add_repository)
# UpdateUrl=http://example.com
