name: Sparsely MacOS Build

on:
  push:
    branches:
      - master
      - main
#      - develop
      - improve_ci_cd
#  pull_request:
#    branches:
      - master
      - main
#      - develop
      
env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Checkout Code
        uses: actions/checkout@v5
        
      - name: Setup CMake 4.1
        uses: jwlawson/actions-setup-cmake@v2
        with:
          # Use '4.1.x' to automatically get the latest 4.1.z release
          cmake-version: '4.1.x'

      - name: Verify Version
        run: cmake --version

      - uses: actions/cache@v5
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: Install Qt6
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.10.0'
          setup-python: 'false' # Add this line
          tools: 'tools_ifw tools_qtcreator,qt.tools.qtcreator'
          add-tools-to-path: 'true'
          # For Linux, it automatically installs required system dependencies
          install-deps: 'true' 
          # Specify additional modules if needed (e.g., qtcharts, qtwebengine)
          modules: 'qtpdf qtwebengine'
          host: 'mac'
          target: 'desktop'
          arch: 'clang_64'
          
#      - name: Install QtIFW
#        uses: jmarrec/setup-qtifw@v1
#        with:
#          qtifw-version: '4.x'
          
      - name: Build & Install
        run: |
          cmake -S sparsely -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install -DCPACK_GENERATOR=IFW
          cmake --build build --target install --config Release
          
      - name: Package with CPack
        run: |
          cd build
          cpack -G IFW
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sparsely-dist
          path: build/*.dmg