name: Sparsely Windows Build

on:
  push:
    branches:
#      - master
      - main
#      - develop
      - build_windows
#  pull_request:
#    branches:
#      - master
      - main
#      - develop
      
env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Checkout Code
        uses: actions/checkout@v5
        
      - name: Setup CMake 4.1
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '4.1.x'

      - name: Verify Version
        run: cmake --version

      - uses: actions/cache@v5
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: Install Qt6
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.10.0'
          setup-python: false
          tools: 'tools_ifw tools_qtcreator,qt.tools.qtcreator'
          add-tools-to-path: true
          install-deps: true
          modules: 'qtpdf qtwebengine'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2022_64'
          
      - name: Set up MSVC (if using MSVC)
        uses: ilammy/msvc-dev-cmd@v1
          
      - name: Build & Install
        run: |
          cmake -S sparsely -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install -DCPACK_GENERATOR=IFW
          cmake --build build --target install --config Release
          
      - name: Package with CPack
        run: |
          cd build
          cpack -G IFW
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sparsely-dist-windows
          path: build/*.exe